# Scoring weights
SEMANTIC_WEIGHT = 0.55
DOMAIN_WEIGHT = 0.45

# Domain score defaults
DEFAULT_DOMAIN_SCORE = 0.5
DECLARED_DOMAIN_SCORE = 0.6

# RLFF update values
RELEVANT_INCREASE = 0.03
IRRELEVANT_DECREASE = 0.07

# Routing
RESPONSE_TIMEOUT_SECONDS = 300  # 5 minutes for hackathon demo
MAX_ATTEMPTS_BEFORE_ESCALATION = 2

# Auth
SECRET_KEY = "your-secret-key-change-this"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24  # 24 hours